package com.thejawnpaul.gptinvestor.analytics.mixpanel

import com.thejawnpaul.gptinvestor.analytics.BuildConfig
import org.koin.core.module.Module
import org.koin.dsl.module

/**
 * Returns a Koin module that overrides the default [NoOpMixpanelProvider] with the real
 * Swift-side provider. Pass a [SwiftMixpanelProvider] instance from the iosApp and include
 * the result in the `modules(...)` call inside `koinConfiguration<GPTKoinApp>`.
 *
 * Usage from Swift (via MainViewController):
 *   MainViewControllerKt.mainViewController(mixpanelProvider: SwiftMixpanelProvider(token: MixpanelProviderModuleKt.mixpanelToken))
 */
fun mixpanelProviderModule(provider: MixpanelProvider): Module = module {
    single<MixpanelProvider> { provider }
}

/**
 * Exposes the build-configuration-specific Mixpanel project token to the Swift iosApp.
 *
 * [BuildConfig] is generated by the buildkonfig Gradle plugin from `local.properties`:
 *   - dev flavour  → MIXPANEL_DEV_TOKEN
 *   - prod/default → MIXPANEL_PROD_TOKEN
 *
 * [BuildConfig] is `internal` and therefore invisible to Swift. This top-level property
 * re-exports the token as part of the public ObjC header so [SwiftMixpanelProvider] can
 * read the correct token without duplicating values on the Swift side.
 *
 * Usage from Swift (after `import ComposeApp`):
 *   SwiftMixpanelProvider(token: MixpanelProviderModuleKt.mixpanelToken)
 */
val mixpanelToken: String
    get() = BuildConfig.MIXPANEL_TOKEN
