import SwiftUI
import ComposeApp
import Mixpanel
import FirebaseCore
import FirebaseCrashlytics
import FirebaseMessaging

class AppDelegate: NSObject, UIApplicationDelegate, MessagingDelegate, UNUserNotificationCenterDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        let fileName: String

        #if DEV
            fileName = "GoogleService-Info-Dev"
        #else
            fileName = "GoogleService-Info-Prod"
        #endif

        if let filePath = Bundle.main.path(forResource: fileName, ofType: "plist"),
           let options = FirebaseOptions(contentsOfFile: filePath) {
            print("FIR Options: Bundle ID: \(options.bundleID) Client ID: \(options.clientID ?? "nil")")
            FirebaseApp.configure(options: options)
        }
        Messaging.messaging().delegate = self

        UNUserNotificationCenter.current().delegate = self

        return true
    }

    @MainActor
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) async
    -> UIBackgroundFetchResult {
        print(userInfo)
        print("Call exportDeliveryMetricsToBigQuery() from AppDelegate")
        Messaging.serviceExtension().exportDeliveryMetricsToBigQuery(withMessageInfo: userInfo)
        return UIBackgroundFetchResult.newData
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification) async
    -> UNNotificationPresentationOptions {
        let userInfo = notification.request.content.userInfo

        print(userInfo)

        return [.list, .banner, .sound]
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse) async {
        let userInfo = response.notification.request.content.userInfo

        print(userInfo)
    }

    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("Failed to register for remote notifications: \(error)")
    }

    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        print("Firebase registration token: \(String(describing: fcmToken))")
        guard let token = fcmToken else { return }
        IosNotificationBridgeKt.onFcmTokenReceived(token: token)
    }
}

@main
struct iOSApp: App {

    /// Single Mixpanel bridge instance for the app lifetime.
    ///
    /// `SwiftMixpanelProvider.init(token:)` calls `Mixpanel.initialize` internally,
    /// so this must be created exactly once. The SwiftUI `App` struct is instantiated
    /// once by the framework, making a stored property the right place for it.
    ///
    /// Token is sourced from the KMP BuildConfig generated by buildkonfig from local.properties
    /// (MIXPANEL_DEV_TOKEN for dev flavour, MIXPANEL_PROD_TOKEN for prod). The `internal`
    /// BuildConfig object is re-exported as the public `mixpanelToken` property in
    /// MixpanelProviderModule.kt so it is visible here via `import ComposeApp`.
    let mixpanelProvider = SwiftMixpanelProvider(token: MixpanelProviderModuleKt.mixpanelToken)
    let youtubePlayerProvider = SwiftYoutubePlayerProvider()

    /// Google Sign-In bridge. The web client ID is the OAuth2 server client ID used by
    /// Firebase; it is sourced from BuildConfig (WEB_CLIENT_ID in local.properties) and
    /// re-exported via `googleSignInWebClientId` in GoogleSignInProviderModule.kt.
    let googleSignInProvider = SwiftGoogleSignInProvider(
        webClientId: GoogleSignInProviderModuleKt.googleSignInWebClientId
    )

    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate

    init() {
        KoinInitKt.initKoin(
            mixpanelProvider: mixpanelProvider,
            youtubePlayerProvider: youtubePlayerProvider,
            googleSignInProvider: googleSignInProvider
        )
    }

    var body: some Scene {
        WindowGroup {
            ContentView(
                mixpanelProvider: mixpanelProvider,
                youtubePlayerProvider: youtubePlayerProvider,
                googleSignInProvider: googleSignInProvider
            )
        }
    }
}
