import SwiftUI
import ComposeApp
import Mixpanel
import FirebaseCore

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        return true
    }
}

@main
struct iOSApp: App {

    /// Single Mixpanel bridge instance for the app lifetime.
    ///
    /// `SwiftMixpanelProvider.init(token:)` calls `Mixpanel.initialize` internally,
    /// so this must be created exactly once. The SwiftUI `App` struct is instantiated
    /// once by the framework, making a stored property the right place for it.
    ///
    /// Token is sourced from the KMP BuildConfig generated by buildkonfig from local.properties
    /// (MIXPANEL_DEV_TOKEN for dev flavour, MIXPANEL_PROD_TOKEN for prod). The `internal`
    /// BuildConfig object is re-exported as the public `mixpanelToken` property in
    /// MixpanelProviderModule.kt so it is visible here via `import ComposeApp`.
    private let mixpanelProvider = SwiftMixpanelProvider(token: MixpanelProviderModuleKt.mixpanelToken)
    
    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate

    var body: some Scene {
        WindowGroup {
            ContentView(mixpanelProvider: mixpanelProvider)
        }
    }
}
